version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=apirestjgmbd
    ports:
      - 3307:3306
    volumes:
      - mysqlvolume:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/apirestjgm
    container_name: apirestjgm
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/apirestjgmbd?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mysqlvolume:
